#ifndef CLIENT_H
#define CLIENT_H
#include <libwebsockets.h>
#include <argtable3.h>
#include <gst/gst.h>
#include <gst/webrtc/webrtc.h>
#include "message_handling.h"
#include "message_protocol.h"
#include "signaling_context.h"


typedef struct {
    struct lws *wsi;
    struct signaling_state *client_state;
    GstElement *webrtcbin;
} CallbackHelper;

int libwebsocket_callback(
    struct lws *wsi, 
    enum lws_callback_reasons reason,
    void *user, 
    void *in, 
    size_t len
);

/* 
 * Updates the local SDP offer in the signaling state.
 *
 * This update is necessary for several reasons:
 *
 * 1. Synchronization:
 *    Ensures that both local and remote peers are working with the most recent SDP offer.
 *
 * 2. Change Detection:
 *    Compares the new SDP offer with the current one. If they are identical,
 *    no update is performed, avoiding unnecessary re-negotiation.
 *
 * 3. Versioning:
 *    Increments a version counter so that the system can track which SDP offer is the latest.
 *    This helps during asynchronous signaling events and multiple negotiation rounds.
 *
 * 4. Robust State Management:
 *    Maintains a correct and up-to-date signaling state that other parts of the system,
 *    such as ICE candidate processing, can rely on.
 */
static void update_offer_state(struct signaling_state *client_state, const char *sdp_str);

/* 
 * Updates the remote SDP answer in the signaling state.
 *
 * This update is necessary for several reasons:
 *
 * 1. Synchronization:
 *    Ensures that the remote SDP answer stored in the state is current,
 *    so that any subsequent operations (such as ICE candidate processing)
 *    can rely on the correct session description.
 *
 * 2. Change Detection:
 *    Compares the new SDP answer with the one already stored.
 *    If they are identical, no update is performed to avoid redundant processing.
 *
 * 3. Versioning:
 *    When a new answer is detected, the global version counter is incremented,
 *    and the new answer's version is recorded.
 *    This helps in tracking the most recent SDP answer in scenarios with multiple negotiation rounds.
 *
 * 4. Robust State Management:
 *    Maintaining the latest remote SDP answer is crucial for ensuring
 *    consistent signaling and media negotiation between peers.
 */
static void update_answer_state(struct signaling_state *client_state, const char *sdp_str);

/* 
 * Adds a new ICE candidate to the signaling state's candidate list.
 *
 * This function is important for the following reasons:
 *
 * 1. State Management:
 *    Each ICE candidate generated during the WebRTC negotiation is added to a list.
 *    This allows the signaling mechanism to keep track of all candidates that may be needed for establishing a peer-to-peer connection.
 *
 * 2. Debugging and Logging:
 *    The function logs the added ICE candidate, which is useful for verifying that the ICE gathering process is working correctly.
 *
 * 3. Robust Negotiation:
 *    Having a complete list of ICE candidates helps in ensuring that the most optimal network path is chosen
 *    and that any network changes can be handled gracefully during the connection.
 */
static void add_ice_candidate_state(struct signaling_state *client_state, gchar *candidate);

/* 
 * Called when an ICE candidate is generated by webrtcbin.
 *
 * This function performs the following tasks:
 * 1. Checks if the ICE candidate is non-empty. If it's empty, the candidate is ignored.
 * 2. Logs the generated ICE candidate for debugging.
 * 3. Updates the signaling state by adding the new ICE candidate.
 * 4. Creates a JSON message for the ICE candidate.
 * 5. Sends the JSON message to the signaling server via the WebSocket connection.
 */
static void on_ice_candidate(
    GstElement *webrtc, 
    guint mline_index, 
    gchar *candidate,
    gpointer user_data
);

/* 
 * Called when negotiation is needed (typically at startup).
 *
 * This function performs the following tasks:
 * 1. Logs that negotiation is needed.
 * 2. Creates a GstPromise that will trigger the on_answer_created callback when an SDP offer is generated.
 * 3. Emits the "create-offer" signal on the webrtcbin element to initiate SDP offer creation.
 */
static void on_negotiation_needed(GstElement *webrtc, gpointer user_data);

/**
 * Callback function for handling dynamic pad addition from the webrtcbin element.
 *
 * When a remote media stream (typically a video RTP stream) arrives, webrtcbin creates a new pad.
 * This callback is invoked to:
 *
 * 1. Retrieve the pad's capabilities (caps) and verify that it represents a video RTP stream.
 *    - If the caps are missing, invalid, or do not indicate a video stream, the pad is ignored.
 *
 * 2. Dynamically create a decoding chain (a sub-bin) to process the incoming media stream.
 *    The decoding chain consists of:
 *      - An RTP depayloader ("rtpvp8depay") to extract payload data.
 *      - A VP8 decoder ("vp8dec") to decode the video stream.
 *      - A videoconvert element ("videoconvert") to convert video formats.
 *      - A queue element ("queue") to smooth out data flow.
 *      - An autovideosink ("autovideosink") to display the video.
 *
 * 3. Create a ghost pad on the newly created bin, so that the bin appears as a single element with a sink pad.
 *
 * 4. Add the new bin to the main pipeline and link the new remote pad from webrtcbin to the ghost pad of this bin.
 *
 * This mechanism allows the GStreamer pipeline to dynamically incorporate and display remote media streams,
 * which is essential for applications like WebRTC where remote streams arrive asynchronously.
 *
 * In case of errors (e.g., missing elements or linking failures), resources are unreferenced appropriately.
 */
static void on_pad_added(GstElement *element, GstPad *pad, gpointer user_data);

/* 
 * Called when an SDP answer is created in response to a received offer.
 *
 * This function performs the following tasks:
 * 1. Extracts the SDP answer from the promise's reply.
 * 2. Converts the SDP answer to a text string and logs it.
 * 3. Updates the local signaling state with the new SDP answer.
 * 4. Sets the local description on the webrtcbin element.
 * 5. Creates a JSON message for the SDP answer and sends it via the signaling server.
 */
 static void on_answer_created_lib(GstPromise *promise, GstElement *webrtcbin, gpointer user_data);

#endif 
