#include <gst/gst.h>
#include <gst/webrtc/webrtc.h>
//#include <gst/rtp/gstrtpbin.h>
#include <glib.h>
#include <libwebsockets.h>
#include <string.h>
#include <stdlib.h>

#include "message_protocol.h"   // For create_json_message() and parse_json_message()
#include "message_handling.h"   // For send_data_to_client()

/* --- Global Variables --- */
static GstElement *pipeline = NULL;
static GstElement *webrtcbin = NULL;
static struct lws_context *ws_context = NULL;
static struct lws *ws_client = NULL;

/* Global signaling state for the client.
 * This state will store the remote SDP offer, our local SDP answer, and ICE candidates.
 */
static struct signaling_state *client_state = NULL;

/* --- Helper Functions to Update signaling_state --- */
static void update_offer_state(const char *sdp_str)
{
    if (!client_state->sdp_offer || strcmp(client_state->sdp_offer, sdp_str) != 0) {
        free(client_state->sdp_offer);
        client_state->sdp_offer = strdup(sdp_str);
        client_state->offer_version = ++client_state->global_version_counter;
        g_print("[State] Updated remote SDP offer (version %lu).\n", client_state->offer_version);
    } else {
        g_print("[State] Received identical SDP offer; no update needed.\n");
    }
}

static void update_answer_state(const char *sdp_str)
{
    if (!client_state->sdp_answer || strcmp(client_state->sdp_answer, sdp_str) != 0) {
        free(client_state->sdp_answer);
        client_state->sdp_answer = strdup(sdp_str);
        client_state->answer_version = ++client_state->global_version_counter;
        g_print("[State] Updated local SDP answer (version %lu).\n", client_state->answer_version);
    } else {
        g_print("[State] Received identical SDP answer; no update needed.\n");
    }
}

static void add_ice_candidate_state(const char *candidate)
{
    /* Simply add every candidate; you might wish to check for duplicates in a full implementation. */
    g_ptr_array_add(client_state->ice_candidates, strdup(candidate));
    g_print("[State] Added ICE candidate to state: %s.\n", candidate);
}

/* --- WebRTC Callbacks --- */

/* Called when an ICE candidate is generated by webrtcbin */
static void on_ice_candidate(GstElement *webrtc, guint mline_index, gchar *candidate, gpointer user_data)
{

    if (candidate == NULL || strlen(candidate) == 0) {
        g_print("[WebRTC] Ignoring empty ICE candidate message.\n");
        return;
    }
    g_print("[WebRTC] ICE candidate generated: %s\n", candidate);
    add_ice_candidate_state(candidate);

    char *json = create_json_message("ice_candidate", candidate);
    if (json) {
        if (send_data_to_client(ws_client, json) == 0)
            g_print("[WebRTC] Sent ICE candidate via signaling server.\n");
        else
            g_printerr("[WebRTC] Failed to send ICE candidate.\n");
        free(json);
    } else {
        g_printerr("[WebRTC] Failed to create JSON for ICE candidate.\n");
    }
}

/* Called when an SDP answer is created in response to a received offer */
static void on_answer_created(GstPromise *promise, gpointer user_data)
{
    GstWebRTCSessionDescription *answer = NULL;
    const GstStructure *reply = gst_promise_get_reply(promise);
    gst_structure_get(reply, "answer", GST_TYPE_WEBRTC_SESSION_DESCRIPTION, &answer, NULL);
    gst_promise_unref(promise);

    if (!answer) {
        g_printerr("[WebRTC] Failed to create answer\n");
        return;
    }

    gchar *sdp_str = gst_sdp_message_as_text(answer->sdp);
    g_print("[WebRTC] Created SDP answer:\n%s\n", sdp_str);

    /* Update our local answer state */
    update_answer_state(sdp_str);

    /* Set our local description */
    g_signal_emit_by_name(webrtcbin, "set-local-description", answer, NULL);

    /* Send the SDP answer via the signaling server */
    char *json = create_json_message("sdp_answer", sdp_str);
    if (json) {
        if (send_data_to_client(ws_client, json) == 0)
            g_print("[WebRTC] Sent SDP answer via signaling server.\n");
        else
            g_printerr("[WebRTC] Failed to send SDP answer.\n");
        free(json);
    } else {
        g_printerr("[WebRTC] Failed to create JSON for SDP answer.\n");
    }

    g_free(sdp_str);
    gst_webrtc_session_description_free(answer);
}

static void on_pad_added(GstElement *element, GstPad *pad, gpointer user_data) {
    GstCaps *caps;
    const gchar *caps_name;
    GstStructure *str;
    GstElement *bin, *depay, *dec, *conv, *queue, *sink;
    GstPad *sinkpad, *ghost_pad, *bin_sink_pad;
    
    /* Get the capabilities of the new pad */
    caps = gst_pad_get_current_caps(pad);
    if (!caps)
        caps = gst_pad_query_caps(pad, NULL);
    if (!caps)
        return;
    
    str = gst_caps_get_structure(caps, 0);
    caps_name = gst_structure_get_name(str);
    g_print("[Receiver] New pad '%s' added from element '%s'\n", caps_name, GST_ELEMENT_NAME(element));

    /* We expect a video RTP stream.
       Optionally, verify that the caps contain a field "media" with value "video".
    */
    {
        const gchar *media = gst_structure_get_string(str, "media");
        if (!media || g_strcmp0(media, "video") != 0) {
            g_print("[Receiver] Ignoring pad because media is not video.\n");
            gst_caps_unref(caps);
            return;
        }
    }

    if (!g_str_has_prefix(caps_name, "application/x-rtp")) {
        g_print("[Receiver] Ignoring pad: caps are not RTP.\n");
        gst_caps_unref(caps);
        return;
    }

    /* Create a new bin to hold the decode chain for the remote stream */
    bin = gst_bin_new("decoder_bin");
    depay = gst_element_factory_make("rtpvp8depay", "depay");
    dec   = gst_element_factory_make("vp8dec", "dec");
    conv  = gst_element_factory_make("videoconvert", "conv");
    queue = gst_element_factory_make("queue", "queue");
    sink  = gst_element_factory_make("autovideosink", "sink");

    if (!bin || !depay || !dec || !conv || !queue || !sink) {
        g_printerr("[Receiver] Failed to create one or more decode chain elements\n");
        if (bin)
            gst_object_unref(bin);
        gst_caps_unref(caps);
        return;
    }

    /* Optionally, disable sync on the sink so frames render as soon as they arrive */
    g_object_set(sink, "sync", FALSE, NULL);

    gst_bin_add_many(GST_BIN(bin), depay, dec, conv, queue, sink, NULL);
    if (!gst_element_link_many(depay, dec, conv, queue, sink, NULL)) {
        g_printerr("[Receiver] Failed to link decode chain elements\n");
        gst_object_unref(bin);
        gst_caps_unref(caps);
        return;
    }

    /* Create a ghost pad for the bin using the depayloader’s sink pad */
    sinkpad = gst_element_get_static_pad(depay, "sink");
    ghost_pad = gst_ghost_pad_new("sink", sinkpad);
    gst_object_unref(sinkpad);
    gst_element_add_pad(bin, ghost_pad);

    /* Add the bin to the main pipeline */
    GstElement *pipeline = GST_ELEMENT(gst_element_get_parent(element));
    gst_bin_add(GST_BIN(pipeline), bin);
    gst_element_sync_state_with_parent(bin);

    /* Link the remote pad from webrtcbin to the ghost pad of our bin */
    bin_sink_pad = gst_element_get_static_pad(bin, "sink");
    if (gst_pad_link(pad, bin_sink_pad) != GST_PAD_LINK_OK) {
        g_printerr("[Receiver] Failed to link remote pad to decoder bin ghost pad\n");
    } else {
        g_print("[Receiver] Successfully linked remote pad to decoder bin\n");
    }
    gst_object_unref(bin_sink_pad);
    gst_object_unref(pipeline);
    gst_caps_unref(caps);
}


/* --- Libwebsockets Client Callback --- */
static int ws_client_callback(struct lws *wsi, enum lws_callback_reasons reason,
                              void *user, void *in, size_t len)
{
    switch (reason) {

    case LWS_CALLBACK_CLIENT_ESTABLISHED:
        g_print("[WS] Connected to signaling server.\n");
        ws_client = wsi;
        break;

    case LWS_CALLBACK_CLIENT_RECEIVE:
    {
        /* Process incoming signaling messages */
        char *msg = strndup((char*)in, len);
        g_print("[WS] Received message: %s\n", msg);
        char *data = NULL;
        MessageType type = parse_json_message(msg, &data);
        free(msg);

        if (type == MSG_TYPE_SDP_OFFER && data) {
            g_print("[WS] Processing SDP offer.\n");
            GstSDPMessage *sdp = NULL;
            if (gst_sdp_message_new(&sdp) != GST_SDP_OK) {
                g_printerr("[WS] Failed to allocate SDP message\n");
                free(data);
                break;
            }
            if (gst_sdp_message_parse_buffer((guint8*)data, strlen(data), sdp) != GST_SDP_OK) {
                g_printerr("[WS] Failed to parse SDP offer\n");
                gst_sdp_message_free(sdp);
                free(data);
                break;
            }
            GstWebRTCSessionDescription *offer =
                gst_webrtc_session_description_new(GST_WEBRTC_SDP_TYPE_OFFER, sdp);
            update_offer_state(data);
            g_signal_emit_by_name(webrtcbin, "set-remote-description", offer, NULL);
            gst_webrtc_session_description_free(offer);

            /* Now create an answer */
            GstPromise *promise = gst_promise_new_with_change_func(on_answer_created, NULL, NULL);
            g_signal_emit_by_name(webrtcbin, "create-answer", NULL, promise);
        } else if (type == MSG_TYPE_ICE_CANDIDATE && data) {
            g_print("[WS] Processing ICE candidate: %s\n", data);
            add_ice_candidate_state(data);
            g_signal_emit_by_name(webrtcbin, "add-ice-candidate", 0, data);
        } else {
            g_print("[WS] Unknown or invalid signaling message received.\n");
        }
        free(data);
        break;
    }

    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
        g_printerr("[WS] Connection error to signaling server.\n");
        ws_client = NULL;
        break;

    case LWS_CALLBACK_CLIENT_CLOSED:
        g_print("[WS] Signaling connection closed.\n");
        ws_client = NULL;
        break;

    default:
        break;
    }
    return 0;
}

/* Libwebsockets protocols for the client */
static const struct lws_protocols ws_protocols[] = {
    {
        .name = "webrtc-protocol",
        .callback = ws_client_callback,
        .per_session_data_size = 0,
        .rx_buffer_size = 4096,
    },
    { NULL, NULL, 0, 0 }
};

/* --- GLib Main Loop Timeout for lws_service --- */
static gboolean lws_service_cb(gpointer user_data)
{
    if (ws_context)
        lws_service(ws_context, 0);
    return TRUE; /* continue calling */
}

/* --- Main Function --- */
int main(int argc, char **argv)
{
    gst_init(&argc, &argv);

    /* Allocate and initialize the client signaling state */
    client_state = calloc(1, sizeof(struct signaling_state));
    if (!client_state) {
        g_printerr("[State] Failed to allocate client signaling state.\n");
        return -1;
    }
    client_state->ice_candidates = g_ptr_array_new();

    /* Create the GStreamer pipeline.
     *
     * This pipeline captures local video (from /dev/video0) and uses a tee to
     * preview it locally (with autovideosink) as well as send it via webrtcbin.
     * Adjust the pipeline string as needed (e.g., to add audio).
     */
    //pipeline = gst_parse_launch(
    //    "v4l2src device=/dev/video0 ! videoconvert ! tee name=t "
    //    "t. ! queue ! videoconvert ! autovideosink sync=false "
    //    "t. ! queue ! videoconvert ! vp8enc ! rtpvp8pay ! rtprtxsend ! "
    //    "webrtcbin name=webrtcbin",
    //    NULL);
    pipeline = gst_parse_launch(
        "webrtcbin name=webrtcbin "
        "webrtcbin. ! rtpvp8depay ! vp8dec ! videoconvert ! autovideosink",
        NULL);
    if (!pipeline) {
        g_printerr("[Main] Failed to create pipeline\n");
        return -1;
    }

    /* Retrieve the webrtcbin element */
    webrtcbin = gst_bin_get_by_name(GST_BIN(pipeline), "webrtcbin");
    if (!webrtcbin) {
        g_printerr("[Main] Failed to get webrtcbin element\n");
        gst_object_unref(pipeline);
        return -1;
    }

    g_object_set(webrtcbin, "stun-server", "stun://stun.l.google.com:19302", NULL);
    g_object_set(webrtcbin, "rtx-payload-type-map", "{96:97}", NULL);
    /* Connect WebRTC signals */
    g_signal_connect(webrtcbin, "on-ice-candidate", G_CALLBACK(on_ice_candidate), NULL);
    //g_signal_connect(webrtcbin, "pad-added", G_CALLBACK(on_pad_added), NULL);

    GstClock *clock = gst_system_clock_obtain();
    gst_pipeline_use_clock(GST_PIPELINE(pipeline), clock);
    gst_object_unref(clock);

    /* Start the pipeline */
    gst_element_set_state(pipeline, GST_STATE_PLAYING);

    /* Set up the libwebsockets client context */
    struct lws_context_creation_info info;
    memset(&info, 0, sizeof(info));
    info.port = CONTEXT_PORT_NO_LISTEN; /* Client mode */
    info.protocols = ws_protocols;
    ws_context = lws_create_context(&info);
    if (!ws_context) {
        g_printerr("[WS] Failed to create libwebsockets context\n");
        gst_object_unref(webrtcbin);
        gst_object_unref(pipeline);
        return -1;
    }

    /* Connect to the signaling server.
     * Adjust the address, port, and path as needed.
     */
    struct lws_client_connect_info ccinfo = {0};
    ccinfo.context = ws_context;
    ccinfo.address = "localhost";   /* Signaling server hostname */
    ccinfo.port = 9000;             /* Signaling server port */
    ccinfo.path = "/";
    ccinfo.host = lws_canonical_hostname(ws_context);
    ccinfo.origin = "origin";
    ccinfo.protocol = ws_protocols[0].name;
    ccinfo.ssl_connection = 0;      /* Use SSL if required */
    ws_client = lws_client_connect_via_info(&ccinfo);
    if (!ws_client) {
        g_printerr("[WS] Failed to connect to signaling server\n");
        lws_context_destroy(ws_context);
        gst_object_unref(webrtcbin);
        gst_object_unref(pipeline);
        return -1;
    }

    /* Create and run the GLib main loop */
    GMainLoop *loop = g_main_loop_new(NULL, FALSE);
    g_timeout_add(10, lws_service_cb, NULL);
    g_print("[Main] Starting main loop...\n");
    g_main_loop_run(loop);

    /* Cleanup */
    gst_element_set_state(pipeline, GST_STATE_NULL);
    gst_object_unref(webrtcbin);
    gst_object_unref(pipeline);
    lws_context_destroy(ws_context);
    g_main_loop_unref(loop);

    /* Free the signaling state */
    free(client_state->sdp_offer);
    free(client_state->sdp_answer);
    if (client_state->ice_candidates) {
        for (guint i = 0; i < client_state->ice_candidates->len; i++) {
            free(g_ptr_array_index(client_state->ice_candidates, i));
        }
        g_ptr_array_free(client_state->ice_candidates, TRUE);
    }
    free(client_state);

    return 0;
}